set nocompatible

filetype off

set rtp+=~/.config/vim/bundle/Vundle.vim

call vundle#begin('~/.config/vim/bundle')

" General
Plugin 'preservim/nerdtree'
Plugin 'mbbill/undotree'
Plugin 'jremmen/vim-ripgrep'
Plugin 'kien/ctrlp.vim'
Plugin 'morhetz/gruvbox'

" Programming
Plugin 'ycm-core/YouCompleteMe'

" Web-dev
Plugin 'mattn/emmet-vim'
Plugin 'Yggdroot/indentLine'
Plugin 'MaxMEllon/vim-jsx-pretty'
Plugin 'tpope/vim-commentary'
Plugin 'dense-analysis/ale'

" Visual aid
Plugin 'itchyny/lightline.vim'

" Writing
Plugin 'godlygeek/tabular'
Plugin 'junegunn/goyo.vim'
" Plugin 'plasticboy/vim-markdown'

call vundle#end()

filetype plugin indent on

syntax on

colorscheme gruvbox

" Sets

set background=dark
set guicursor=
set relativenumber
set nohlsearch
set hidden
set noerrorbells
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set nu
set smartcase
set wrap
set smartcase
set encoding=utf-8
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set incsearch
set termguicolors
set scrolloff=8
set noshowmode
set completeopt=menuone,noinsert,noselect
set shortmess+=c
set cmdheight=2
set updatetime=50
set viminfo+=n~/.config/vim/viminfo
set runtimepath+=~/.config/vim
set ruler

set laststatus=2
set noshowmode

" Lets

let mapleader="<"

let g:lightline = {'colorscheme': 'jellybeans',}

" Custom mappings

nmap <Leader>. :tabn<CR>
nmap <Leader>, :tabp<CR>

" Custom Plugin Mappings
nmap <Leader>n :NERDTreeToggle<CR>
nmap <Leader>g :Goyo<CR>

" Terminal color fix
if &term =~ '256color'
    set t_ut=
endif

let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

" Plugin settings
let g:vim_markdown_folding_disabled = 1

" Retarded zsh fix for cursor shape
autocmd VimEnter * silent exec "! echo -ne '\e[1 q'"
autocmd VimLeave * silent exec "! echo -ne '\e[5 q'" 

" Autocmds
" autocmd vimenter * NERDTree "IDK wether to enable this, getting mixed
" feelings
autocmd! BufWritePost config.h !sudo make clean install
autocmd! bufwritepost .vimrc source %
