set nocompatible

filetype off
set rtp+=~/.config/vim/bundle/Vundle.vim

call vundle#begin('~/.config/vim/bundle')

" General
Plugin 'preservim/nerdtree'
Plugin 'mbbill/undotree'
Plugin 'kien/ctrlp.vim' 
Plugin 'morhetz/gruvbox'

" Programming 
Plugin 'ycm-core/YouCompleteMe' 

" Web-dev
"Plugin 'mattn/emmet-vim' 
"Plugin 'Yggdroot/indentLine'
"Plugin 'tpope/vim-commentary'
"Plugin 'dense-analysis/ale'

" Visual aid
Plugin 'itchyny/lightline.vim'
Plugin 'junegunn/goyo.vim'

call vundle#end()

filetype plugin indent on

syntax on

colorscheme gruvbox

" Sets

set background=dark
set relativenumber
set nohlsearch
set hidden
set noerrorbells
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set nu
set smartcase
set wrap
set smartcase
set encoding=utf-8
set noswapfile
set nobackup
set undodir=~/.config/vim/undodir
set undofile
set incsearch
set termguicolors
set scrolloff=8
set noshowmode
set completeopt=menuone,noinsert,noselect
set shortmess+=c
set cmdheight=2
set updatetime=50
set viminfo+=n~/.config/vim/viminfo
set runtimepath+=~/.config/vim
set omnifunc=syntaxcomplete#Complete
set ruler
set laststatus=2
set noshowmode

" Lets

let mapleader="<"

let g:lightline = {'colorscheme': 'jellybeans',}
let g:ycm_global_ycm_extra_conf = '/home/konsta/config/vim/bundle/YouCompleteMe/.ycm_extra_conf.py'

" Custom aliases
cnoreabbrev W w !sudo tee %

" Custom mappings
nmap sh :vertical-resize -1<CR>
nmap sl :vertical-resize +1<CR>
nmap sj :resize +1<CR>
nmap sk :resize -1<CR>

" Move to window
nmap mh <C-w>h
nmap ml <C-w>l
nmap mj <C-w>j
nmap mk <C-w>k

" Move to tab
nmap zl :tabn<CR>
nmap zh :tabp<CR>

" Custom Plugin Mappings
nmap <Leader>n :NERDTreeToggle<CR>
nmap <Leader>g :Goyo<CR>

" Terminal color fix
set t_Co=256

if &term =~ '256color'
    set t_ut=
endif

let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

" Start autocompletion after 4 chars
let g:ycm_min_num_of_chars_for_completion = 4
let g:ycm_min_num_identifier_candidate_chars = 4
let g:ycm_enable_diagnostic_highlighting = 0

" Retarded zsh fix for cursor shape
autocmd VimEnter * silent exec "! echo -ne '\e[1 q'"
autocmd VimLeave * silent exec "! echo -ne '\e[5 q'" 

autocmd! BufWritePost vimrc source %
