#!/bin/sh

userresources=$HOME/.config/X11/Xresources

# merge in xresources
if [ -f "$userresources" ]; then
    xrdb -merge "$userresources" 
fi

# Source xinitrc.d
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# start some nice programs
desktop-xrandr &
picom &
dbus-launch startdwm
