#! /bin/sh

status=$(mpris-ctl info "%player_name | %track_name - %artist_name" | grep Spotify | awk '{print $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20}')
echo $status
