#!/bin/sh

date=$(date-status)
time=$(time-status)
volume=$(volume-status)
weather=$(weather-status)
btc=$(btc-status)
cputemp=$(cpu-t-status)
ip=$(ip-status)

status="$ip | $cputemp | $btc | $weather | $volume | $time | $date"

xsetroot -name "$status"
